default:
  # Discord API token
  token:
  # AMQP credentials
  amqp:
    user:
    password:
    broker_address:
    virtual_host:
    url: "@format amqps://{this.AMQP_USER}:{this.AMQP_PASSWORD}@{this.AMQP_BROKER_ADDRESS}/{this.AMQP_VIRTUAL_HOST}"
  # Spotify client id + secret
  spotify_client:
  spotify_secret:
